# Generated by Django 4.2.20 on 2025-04-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='release_year',
        ),
        migrations.AddField(
            model_name='film',
            name='duration',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
