# Generated by Django 4.2.20 on 2025-04-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0002_remove_film_release_year_film_duration_film_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film_poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('poster_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
