# Generated by Django 4.2.20 on 2025-04-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0003_film_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film_poster',
        ),
        migrations.RemoveField(
            model_name='film',
            name='description',
        ),
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
